"""init schema

Revision ID: 0f279fc188f6
Revises: 24e486c7e6a7
Create Date: 2026-05-06 07:15:21.036244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f279fc188f6'
down_revision: Union[str, Sequence[str], None] = '24e486c7e6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('representative_docs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'representative_docs')
    # ### end Alembic commands ###
