"""init schema

Revision ID: 24e486c7e6a7
Revises: 2094e58d9e01
Create Date: 2026-05-05 23:45:07.844132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e486c7e6a7'
down_revision: Union[str, Sequence[str], None] = '2094e58d9e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_description', sa.Text(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('article_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_cluster_id'), 'clusters', ['cluster_id'], unique=True)
    op.add_column('articles', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_articles_cluster_id'), 'articles', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_cluster_id'), table_name='articles')
    op.drop_column('articles', 'cluster_id')
    op.drop_index(op.f('ix_clusters_cluster_id'), table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
