"""init

Revision ID: fa60d5698a2b
Revises: f6363172a017
Create Date: 2026-04-03 22:29:16.732031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa60d5698a2b'
down_revision: Union[str, Sequence[str], None] = 'f6363172a017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arxiv_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arxiv_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract_text', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('primary_category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arxiv_articles_arxiv_id'), 'arxiv_articles', ['arxiv_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arxiv_articles_arxiv_id'), table_name='arxiv_articles')
    op.drop_table('arxiv_articles')
    # ### end Alembic commands ###
